{
  imports = [
    ./common/gnome.nix
    ./common/hardening.nix
    ./common/home-manager.nix
    ./common/locale.nix
    ./common/misc.nix
    ./common/networking.nix
    ./common/nh.nix
    ./common/nix.nix
    ./common/openssh.nix
    ./common/setUserIcons.nix
    ./common/sops.nix
    ./common/tailscale.nix
    ./common/time.nix
    ./common/usbguard.nix
    ./common/users.nix
    ./features/bootloader.nix
    ./features/firewalld.nix
    ./features/home-wifi.nix
    ./features/printer.nix
    ./features/fprint.nix
    ./features/plymouth.nix
    ./features/virt-manager.nix
    ./features/podman.nix
  ];
}
