name: Flake Check

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

jobs:
  flake-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v22

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v14

      - name: Run flake check
        run: nix flake check
